# **File Handling using read()**

In [ ]:
# creating dempo file

f = open("demo.txt",'w')
f.write("Line1: Hellow\nLine2: World\nLine3: python")
f.close()

# Reading form the file
f = open("demo.txt",'r')
d =f.read()

print(d)
print("Type:" ,type(d))  # checking data type
f.close()




Line1: Hellow
Line2: World
Line3: python
Type: <class 'str'>


# **File Handling using Readline**

In [ ]:
f = open('demo.txt','r')
print("file reading using readline ")
Line1 = f.readline()
print(Line1,end='')
Line2 = f.readline()
print(Line2,end='')
Line3 = f.readline()
print(Line3,end='')
f.close

file reading using readline 
Line1: Hellow
Line2: World
Line3: python

<function TextIOWrapper.close()>

# **Using context manager with** automatically open and close file

In [ ]:
with open('demo.txt','r') as f :
  data = f.read()
  print("using with:" ,data)
  print("File close automatically")

using with: Line1: Hellow
Line2: World
Line3: python
File close automatically


# **tell() gives current pointer position. seek() moves pointer.**

In [ ]:
f= open("demo.txt",'r')
print("Current Position:" ,f.tell())
data = f.read(10)
print(data, f.tell())
f.seek(0)
print("Position after seek(0)" , f.tell())
f.close()

Current Position: 0
Line1: Hel 10
Position after seek(0) 0


# **Working with binary**

In [ ]:
# write in binary mode

with open("data.bin","wb") as f:
  f.write(b"Hello Binary\n")
  f.write(b"1234565677")

with open("data.bin" ,'rb') as f:
   print("Binary read: " ,f.read())
   f.seek(6)
   print("After seek:",f.read())



Binary read:  b'Hello Binary\n1234565677'
After seek: b'Binary\n1234565677'


# **6. SERIALIZATION AND DESERIALIZATION USING pickle**
Definition: Serialization = Convert object to bytes to save in file.

Deserialization = Convert bytes back to object.

In [ ]:
import pickle

data = {"name":"Ali" ,"marls ":[90,80,70]}

# serilization :object ->bytes->file
with open("data.pkl" ,'wb') as f:
  pickle.dump(data,f) #dump conver obj to bytes and write to file
  print("Data serilization and saved ")

  ## DESERIALIZATION: file -> bytes -> object
with open("data.pkl", "rb") as f: # Read binary
    loaded_data = pickle.load(f) # load() converts bytes back to object
    print("Data deserialized:", loaded_data) # Print recovered object


Data serilization and saved 
Data deserialized: {'name': 'Ali', 'marls ': [90, 80, 70]}


# **7. CUSTOM OBJECT PICKLING**
You can pickle your own class objects too.


In [ ]:
import pickle
class Student:
  def __init__(self, name, roll_no):
    self.name=name
    self.roll_no = roll_no
  def display(self):
    print(f"Name :{self.name} ,\nROllNo:{self.roll_no}")

s1 =Student("sara",101)

# pickele the object
with open ("student.pkl" , 'wb')as f :
  pickle.dump(s1,f)  #save obj to file

# Unpickle the object
with open("student.pkl",'rb') as f:
  s2= pickle.load(f)
  s2.display()



Name :sara ,
ROllNo:101


# **8. DECORATOR**
decoorator is a function that takes another function and add extra functionality

In [ ]:
def my_decorator(func):
  def wrapper():
    print("Befor function call:")
    func()
    print("After function call")

  return wrapper

@my_decorator
def greet():
  print("Hello!")


greet()

Befor function call:
Hello!
After function call


# **9. NAMESPACES, SCOPES, AND LEGB RULE**
Definition: LEGB = Local, Enclosing, Global, Built-in. Python searches variable in this order

In [ ]:
x = "golbal"
def outer():

  x = "Encloseing" #varriable in outer function
  def inner():
    x = "Local" #varrilbe in local scope
    print("Local x:",x)

    print("BuiltIn len:" , len("test"))

  inner()
  print("Enclosing x :", x)
outer()
print("Global x: ",x)



Local x: Local
BuiltIn len: 4
Enclosing x : Encloseing
Global x:  golbal


# **NUMPY in python**

**Creating Numpy Arrays**

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

# dtype
np.array([1,2,3],dtype= float)

# with reshape
np.arange(1,11,2)
np.arange(16).reshape(2,2,2,2)


[[1 2 3]
 [4 5 6]]


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.9904888 , 0.31289734, 0.04616685, 0.12559533],
       [0.45347954, 0.32832661, 0.063684  , 0.96077543],
       [0.68909664, 0.13375593, 0.81486489, 0.79731317]])

In [ ]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array attiribues**

In [ ]:
a1=np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.ndim

3

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.itemsize

8

# **Changing datatypes**

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a2)
# arithmatic
a1**2

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1==15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# **Array functions**

In [ ]:
a1 =np.random.random((3,3))
a1 =np.round(a1*100)
a1

array([[16., 97., 87.],
       [25., 80.,  6.],
       [70., 25., 80.]])

In [ ]:
# max/min/sum/prod
# 0->col and 1-> row
np.prod(a1,axis=0)

array([ 28000., 194000.,  41760.])

In [ ]:
from contextlib import AsyncExitStack
# mean/median/std/var
np.var(a1,axis=1)

array([1300.22222222,  984.66666667,  572.22222222])

In [ ]:
# trigonomoetiric functions
np.sin(a1)

array([[-0.28790332,  0.37960774, -0.82181784],
       [-0.13235175, -0.99388865, -0.2794155 ],
       [ 0.77389068, -0.13235175, -0.99388865]])

In [ ]:
# dot prodeuct
a2=np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[8.88611052e+06, 1.33833472e+42, 6.07603023e+37],
       [7.20048993e+10, 5.54062238e+34, 4.03428793e+02],
       [2.51543867e+30, 7.20048993e+10, 5.54062238e+34]])

In [ ]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[27., 46.,  9.],
       [51., 61., 61.]])

# **# Indexing and slicing**

In [ ]:

a1=np.arange(10)
a2= np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,1,1]

np.int64(3)

In [ ]:
a3[1,1,1]

np.int64(7)

In [ ]:
a3[1,0,0]

np.int64(4)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:6]

array([2, 3, 4, 5])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:2]
a2[1:3,1:3]
a2[2:3,2:4]
a2[0:1,2:4]
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1:2,::3]

array([[4, 7]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a3 =np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0 ,::2]

array([[ 0,  2],
       [18, 20]])

# **Iterating**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a2:
  # if a1<=8:
  #   break
  # else:
    # print(a1)
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
for i in np.nditer(a3):
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [

# **Reshape**

In [ ]:
# transpone
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# reveal -> covert all dimenetiona array in to 1 array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# **stacking**

In [ ]:
# 2 arrays ko jorna combine krna . ->horizontally,->vertically
# use for multiple data combination like database sa data aa rha ha local ma ha etc

a4 =np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# horizontal

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical
np.vstack((a4,a5,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# **Spliting **
**Opposite of stacking** use tab ho ga jab humhy ak hi resours sa data fatch krna ha

In [ ]:
# horizontal split
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical split
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]